apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel-app.fullname" . }}-traefik
  labels:
    {{- include "laravel-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: traefik
spec:
  type: {{ .Values.traefik.service.type }}
  ports:
  - port: {{ .Values.traefik.service.ports.web }}
    targetPort: web
    protocol: TCP
    name: web
  - port: {{ .Values.traefik.service.ports.websecure }}
    targetPort: websecure
    protocol: TCP
    name: websecure
  - port: 8080
    targetPort: dashboard
    protocol: TCP
    name: dashboard
  selector:
    {{- include "laravel-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: traefik
